apiVersion: v1
kind: Pod
metadata:
  name: demo-pod
spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: disk
            operator: In
            values:
            - P1
        topologyKey: topology.kubernetes.io/zone
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: disk
              operator: In
              values:
              - p2
          topologyKey: topology.kubernetes.io/zone
  containers:
  - name: demo
    image: nginx
